"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0)lu2mik4_mv5mv%3p@zd)%#neueh1a3n6i9kond$9n-lx&+@@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'hrm.ezygrocery.com',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '*'  # Keep wildcard for development
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    
    # Local apps
    'core',
    'hr',
'zktest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unfold Admin Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "HR Payroll Admin Panel",
    "SITE_HEADER": "HR Payroll Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "252 254 235",   # Very light lime
            "100": "247 252 213",  # Light lime
            "200": "238 248 178",  # Lighter lime
            "300": "226 242 142",  # Light lime green
            "400": "208 234 106",  # Medium lime
            "500": "196 216 46",   # Main lime color (#c4d82e)
            "600": "168 184 42",   # Darker lime
            "700": "140 154 35",   # Dark lime
            "800": "112 123 28",   # Darker
            "900": "84 92 21",     # Very dark lime
            "950": "56 61 14",     # Darkest lime
        },
    },
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css"),
        lambda request: static("admin/css/custom_tabs.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("core:dashboard"),
                    },
                ],
            },
            {
                "title": _("Core Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("User Profiles"),
                        "icon": "account_circle",
                        "link": admin_changelist("core", "userprofile"),
                        "permission": lambda request: request.user.has_perm("core.view_userprofile"),
                    },
                    {
                        "title": _("Companies"),
                        "icon": "business",
                        "link": admin_changelist("core", "company"),
                        "permission": lambda request: request.user.has_perm("core.view_company"),
                    },
                    {
                        "title": _("Projects"),
                        "icon": "folder_special",
                        "link": admin_changelist("core", "project"),
                        "permission": lambda request: request.user.has_perm("core.view_project"),
                    },
                    {
                        "title": _("Tasks"),
                        "icon": "task",
                        "link": admin_changelist("core", "task"),
                        "permission": lambda request: request.user.has_perm("core.view_task"),
                    },
                    {
                        "title": _("Task Comments"),
                        "icon": "comment",
                        "link": admin_changelist("core", "taskcomment"),
                        "permission": lambda request: request.user.has_perm("core.view_taskcomment"),
                    },
                ],
            },
            # {
            #     "title": _("Reports"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Task Report"),
            #             "icon": "assessment",
            #             "link": lambda request: reverse_lazy("core:task-report"),
            #             "permission": lambda request: request.user.has_perm("core.view_task"),
            #         },
            #         {
            #             "title": _("Attendance Report"),
            #             "icon": "fact_check",
            #             "link": lambda request: reverse_lazy("hr:attendance-report"),
            #             "permission": lambda request: request.user.has_perm("hr.view_attendance"),
            #         },
            #         {
            #             "title": _("Attendance Summary"),
            #             "icon": "summarize",
            #             "link": lambda request: reverse_lazy("hr:attendance-summary-report"),
            #             "permission": lambda request: request.user.has_perm("hr.view_attendance"),
            #         },
            #         {
            #             "title": _("Payroll Summary"),
            #             "icon": "payments",
            #             "link": lambda request: reverse_lazy("hr:payroll-summary-report"),
            #             "permission": lambda request: request.user.has_perm("hr.view_employee"),
            #         },
            #     ],
            # },
            # ==================== HR SYSTEM ====================
            # {
            #     "title": _("🏢 HR SYSTEM"),
            #     "separator": True,
            #     "collapsible": False,
            #     "items": [],
            # },
            # {
            #     "title": _("HR Management"),
            #     "separator": False,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Departments"),
            #             "icon": "corporate_fare",
            #             "link": admin_changelist("hr", "department"),
            #             "permission": lambda request: request.user.has_perm("hr.view_department"),
            #         },
            #         {
            #             "title": _("Designations"),
            #             "icon": "badge",
            #             "link": admin_changelist("hr", "designation"),
            #             "permission": lambda request: request.user.has_perm("hr.view_designation"),
            #         },
            #         {
            #             "title": _("Shifts"),
            #             "icon": "schedule",
            #             "link": admin_changelist("hr", "shift"),
            #             "permission": lambda request: request.user.has_perm("hr.view_shift"),
            #         },
            #         {
            #             "title": _("Employees"),
            #             "icon": "groups",
            #             "link": admin_changelist("hr", "employee"),
            #             "permission": lambda request: request.user.has_perm("hr.view_employee"),
            #         },
            #     ],
            # },
            # {
            #     "title": _("HR Attendance"),
            #     "separator": False,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("ZK Devices"),
            #             "icon": "fingerprint",
            #             "link": admin_changelist("hr", "zkdevice"),
            #             "permission": lambda request: request.user.has_perm("hr.view_zkdevice"),
            #         },
            #         {
            #             "title": _("Attendance Logs"),
            #             "icon": "fact_check",
            #             "link": admin_changelist("hr", "attendancelog"),
            #             "permission": lambda request: request.user.has_perm("hr.view_attendancelog"),
            #         },
            #         {
            #             "title": _("Attendance Records"),
            #             "icon": "event_available",
            #             "link": admin_changelist("hr", "attendance"),
            #             "permission": lambda request: request.user.has_perm("hr.view_attendance"),
            #         },
            #         {
            #             "title": _("Attendance Config"),
            #             "icon": "settings",
            #             "link": admin_changelist("hr", "attendanceprocessorconfiguration"),
            #             "permission": lambda request: request.user.has_perm("hr.view_attendanceprocessorconfiguration"),
            #         },
            #     ],
            # },
            # {
            #     "title": _("HR Leave & Overtime"),
            #     "separator": False,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Leave Types"),
            #             "icon": "category",
            #             "link": admin_changelist("hr", "leavetype"),
            #             "permission": lambda request: request.user.has_perm("hr.view_leavetype"),
            #         },
            #         {
            #             "title": _("Leave Balances"),
            #             "icon": "account_balance_wallet",
            #             "link": admin_changelist("hr", "leavebalance"),
            #             "permission": lambda request: request.user.has_perm("hr.view_leavebalance"),
            #         },
            #         {
            #             "title": _("Leave Applications"),
            #             "icon": "request_page",
            #             "link": admin_changelist("hr", "leaveapplication"),
            #             "permission": lambda request: request.user.has_perm("hr.view_leaveapplication"),
            #         },
            #         {
            #             "title": _("Overtime"),
            #             "icon": "more_time",
            #             "link": admin_changelist("hr", "overtime"),
            #             "permission": lambda request: request.user.has_perm("hr.view_overtime"),
            #         },
            #     ],
            # },
            # {
            #     "title": _("HR Scheduling"),
            #     "separator": False,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Holidays"),
            #             "icon": "celebration",
            #             "link": admin_changelist("hr", "holiday"),
            #             "permission": lambda request: request.user.has_perm("hr.view_holiday"),
            #         },
            #         {
            #             "title": _("Rosters"),
            #             "icon": "calendar_month",
            #             "link": admin_changelist("hr", "roster"),
            #             "permission": lambda request: request.user.has_perm("hr.view_roster"),
            #         },
            #         {
            #             "title": _("Roster Assignments"),
            #             "icon": "assignment_ind",
            #             "link": admin_changelist("hr", "rosterassignment"),
            #             "permission": lambda request: request.user.has_perm("hr.view_rosterassignment"),
            #         },
            #         {
            #             "title": _("Roster Days"),
            #             "icon": "event_note",
            #             "link": admin_changelist("hr", "rosterday"),
            #             "permission": lambda request: request.user.has_perm("hr.view_rosterday"),
            #         },
            #     ],
            # },
            # {
            #     "title": _("HR Notices"),
            #     "separator": False,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Notices"),
            #             "icon": "campaign",
            #             "link": admin_changelist("hr", "notice"),
            #             "permission": lambda request: request.user.has_perm("hr.view_notice"),
            #         },
            #     ],
            # },
            # ==================== ZKTEST SYSTEM ====================
            {
                "title": _("🔧 ZKTest System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    # Management
                    {
                        "title": _("Employees"),
                        "icon": "groups",
                        "link": admin_changelist("zktest", "employee"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employee"),
                    },
                    {
                        "title": _("Departments"),
                        "icon": "corporate_fare",
                        "link": admin_changelist("zktest", "department"),
                        "permission": lambda request: request.user.has_perm("zktest.view_department"),
                    },
                    {
                        "title": _("Designations"),
                        "icon": "badge",
                        "link": admin_changelist("zktest", "designation"),
                        "permission": lambda request: request.user.has_perm("zktest.view_designation"),
                    },
                    {
                        "title": _("Shifts"),
                        "icon": "schedule",
                        "link": admin_changelist("zktest", "shift"),
                        "permission": lambda request: request.user.has_perm("zktest.view_shift"),
                    },
                    # Employee Details
                    {
                        "title": _("Personal Info"),
                        "icon": "person_outline",
                        "link": admin_changelist("zktest", "employeepersonalinfo"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employeepersonalinfo"),
                    },
                    {
                        "title": _("Education"),
                        "icon": "school",
                        "link": admin_changelist("zktest", "employeeeducation"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employeeeducation"),
                    },
                    {
                        "title": _("Salary"),
                        "icon": "payments",
                        "link": admin_changelist("zktest", "employeesalary"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employeesalary"),
                    },
                    {
                        "title": _("Skills"),
                        "icon": "psychology",
                        "link": admin_changelist("zktest", "employeeskill"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employeeskill"),
                    },
                    # Attendance
                    {
                        "title": _("Attendance Logs"),
                        "icon": "fingerprint",
                        "link": admin_changelist("zktest", "attendancelog"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                    {
                        "title": _("Daily Attendance"),
                        "icon": "event_available",
                        "link": admin_changelist("zktest", "attendance"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendance"),
                    },
                    # Reports
                    {
                        "title": _("📊 Attendance Log Report"),
                        "icon": "assessment",
                        "link": lambda request: reverse_lazy("zktest:attendance-log-report"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                    {
                        "title": _("📊 Daily Attendance Report"),
                        "icon": "summarize",
                        "link": lambda request: reverse_lazy("zktest:daily-attendance-report"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                    # Leave & Overtime
                    {
                        "title": _("Leave Types"),
                        "icon": "category",
                        "link": admin_changelist("zktest", "leavetype"),
                        "permission": lambda request: request.user.has_perm("zktest.view_leavetype"),
                    },
                    {
                        "title": _("Leave Balances"),
                        "icon": "account_balance_wallet",
                        "link": admin_changelist("zktest", "leavebalance"),
                        "permission": lambda request: request.user.has_perm("zktest.view_leavebalance"),
                    },
                    {
                        "title": _("Leave Applications"),
                        "icon": "request_page",
                        "link": admin_changelist("zktest", "leaveapplication"),
                        "permission": lambda request: request.user.has_perm("zktest.view_leaveapplication"),
                    },
                    {
                        "title": _("Overtime"),
                        "icon": "more_time",
                        "link": admin_changelist("zktest", "overtime"),
                        "permission": lambda request: request.user.has_perm("zktest.view_overtime"),
                    },
                    # Scheduling
                    {
                        "title": _("Holidays"),
                        "icon": "celebration",
                        "link": admin_changelist("zktest", "holiday"),
                        "permission": lambda request: request.user.has_perm("zktest.view_holiday"),
                    },
                    {
                        "title": _("Rosters"),
                        "icon": "calendar_month",
                        "link": admin_changelist("zktest", "roster"),
                        "permission": lambda request: request.user.has_perm("zktest.view_roster"),
                    },
                    {
                        "title": _("Roster Assignments"),
                        "icon": "assignment_ind",
                        "link": admin_changelist("zktest", "rosterassignment"),
                        "permission": lambda request: request.user.has_perm("zktest.view_rosterassignment"),
                    },
                    {
                        "title": _("Roster Days"),
                        "icon": "event_note",
                        "link": admin_changelist("zktest", "rosterday"),
                        "permission": lambda request: request.user.has_perm("zktest.view_rosterday"),
                    },
                    # Other
                    {
                        "title": _("Notices"),
                        "icon": "campaign",
                        "link": admin_changelist("zktest", "notice"),
                        "permission": lambda request: request.user.has_perm("zktest.view_notice"),
                    },
                    {
                        "title": _("Locations"),
                        "icon": "location_on",
                        "link": admin_changelist("zktest", "location"),
                        "permission": lambda request: request.user.has_perm("zktest.view_location"),
                    },
                    {
                        "title": _("User Locations"),
                        "icon": "my_location",
                        "link": admin_changelist("zktest", "userlocation"),
                        "permission": lambda request: request.user.has_perm("zktest.view_userlocation"),
                    },
                ],
            },
            {
                "title": _("Authentication & Authorization"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """
    Callback to show environment badge in admin
    """
    return ["Development", "warning"]


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow ZKTeco device to push data
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATETIME_INPUT_FORMATS': [
        '%Y-%m-%dT%H:%M:%S%z',
        '%Y-%m-%dT%H:%M:%S.%f%z',
        '%Y-%m-%d %H:%M:%S',
        '%Y-%m-%d %H:%M:%S.%f',
        'iso-8601',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}
