"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0)lu2mik4_mv5mv%3p@zd)%#neueh1a3n6i9kond$9n-lx&+@@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'hrm.ezydream.com',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '*',  # এখানে comma ছিল না
    '195.35.45.104'
]

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    
    # Local apps
    'core',
    'hr',
'zktest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Unfold Admin Configuration for settings.py
Copy this UNFOLD config to your settings.py
"""

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")


# Complete UNFOLD Configuration - paste in settings.py
UNFOLD = {
    "SITE_TITLE": "HR Payroll Admin Panel",
    "SITE_HEADER": "HR Payroll Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "252 254 235",
            "100": "247 252 213",
            "200": "238 248 178",
            "300": "226 242 142",
            "400": "208 234 106",
            "500": "196 216 46",
            "600": "168 184 42",
            "700": "140 154 35",
            "800": "112 123 28",
            "900": "84 92 21",
            "950": "56 61 14",
        },
    },
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css"),
        lambda request: static("admin/css/custom_tabs.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            # ==================== DASHBOARD ====================
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("core:dashboard"),
                    },
                ],
            },
                        # ==================== REPORTS ====================
            {
                "title": _("Reports"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Attendance Log Report"),
                        "icon": "assessment",
                        "link": lambda request: reverse_lazy("zktest:attendance-log-report"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                    {
                        "title": _("Daily Attendance Report"),
                        "icon": "summarize",
                        "link": lambda request: reverse_lazy("zktest:daily-attendance-report"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                ],
            },
            


                        # ==================== HR MANAGEMENT ====================
            {
                "title": _("HR Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Employees"),
                        "icon": "people",
                        "link": admin_changelist("zktest", "employee"),
                        "permission": lambda request: request.user.has_perm("zktest.view_employee"),
                    },
                    {
                        "title": _("Departments"),
                        "icon": "corporate_fare",
                        "link": admin_changelist("zktest", "department"),
                        "permission": lambda request: request.user.has_perm("zktest.view_department"),
                    },
                    {
                        "title": _("Designations"),
                        "icon": "work",
                        "link": admin_changelist("zktest", "designation"),
                        "permission": lambda request: request.user.has_perm("zktest.view_designation"),
                    },
                    {
                        "title": _("Shifts"),
                        "icon": "access_time",
                        "link": admin_changelist("zktest", "shift"),
                        "permission": lambda request: request.user.has_perm("zktest.view_shift"),
                    },
                ],
            },

                        # ==================== ATTENDANCE LOGS ====================
            {
                "title": _("Attendance Logs"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Attendance Logs"),
                        "icon": "schedule",
                        "link": admin_changelist("zktest", "attendancelog"),
                        "permission": lambda request: request.user.has_perm("zktest.view_attendancelog"),
                    },
                    {
                        "title": _("Operation Logs"),
                        "icon": "history",
                        "link": admin_changelist("zktest", "operationlog"),
                        "permission": lambda request: request.user.has_perm("zktest.view_operationlog"),
                    },
                ],
            },
            # ==================== CORE MANAGEMENT ====================
            # {
            #     "title": _("Core Management"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("User Profiles"),
            #             "icon": "account_circle",
            #             "link": admin_changelist("core", "userprofile"),
            #             "permission": lambda request: request.user.has_perm("core.view_userprofile"),
            #         },
            #         {
            #             "title": _("Companies"),
            #             "icon": "business",
            #             "link": admin_changelist("core", "company"),
            #             "permission": lambda request: request.user.has_perm("core.view_company"),
            #         },
            #         {
            #             "title": _("Projects"),
            #             "icon": "folder_special",
            #             "link": admin_changelist("core", "project"),
            #             "permission": lambda request: request.user.has_perm("core.view_project"),
            #         },
            #         {
            #             "title": _("Tasks"),
            #             "icon": "task",
            #             "link": admin_changelist("core", "task"),
            #             "permission": lambda request: request.user.has_perm("core.view_task"),
            #         },
            #         {
            #             "title": _("Task Comments"),
            #             "icon": "comment",
            #             "link": admin_changelist("core", "taskcomment"),
            #             "permission": lambda request: request.user.has_perm("core.view_taskcomment"),
            #         },
            #     ],
            # },
            

            
            # ==================== ATTENDANCE & ROSTER ====================
            # {
            #     "title": _("Attendance & Roster"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Attendance Records"),
            #             "icon": "event_available",
            #             "link": admin_changelist("zktest", "attendance"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_attendance"),
            #         },
            #         {
            #             "title": _("Overtime"),
            #             "icon": "schedule",
            #             "link": admin_changelist("zktest", "overtime"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_overtime"),
            #         },
            #         {
            #             "title": _("Rosters"),
            #             "icon": "calendar_today",
            #             "link": admin_changelist("zktest", "roster"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_roster"),
            #         },
            #         {
            #             "title": _("Roster Assignments"),
            #             "icon": "assignment",
            #             "link": admin_changelist("zktest", "rosterassignment"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_rosterassignment"),
            #         },
            #         {
            #             "title": _("Roster Days"),
            #             "icon": "date_range",
            #             "link": admin_changelist("zktest", "rosterday"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_rosterday"),
            #         },
            #     ],
            # },
            
            # ==================== LEAVE MANAGEMENT ====================
            # {
            #     "title": _("Leave Management"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Leave Applications"),
            #             "icon": "event_busy",
            #             "link": admin_changelist("zktest", "leaveapplication"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_leaveapplication"),
            #         },
            #         {
            #             "title": _("Leave Balances"),
            #             "icon": "account_balance_wallet",
            #             "link": admin_changelist("zktest", "leavebalance"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_leavebalance"),
            #         },
            #         {
            #             "title": _("Leave Types"),
            #             "icon": "category",
            #             "link": admin_changelist("zktest", "leavetype"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_leavetype"),
            #         },
            #         {
            #             "title": _("Holidays"),
            #             "icon": "celebration",
            #             "link": admin_changelist("zktest", "holiday"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_holiday"),
            #         },
            #     ],
            # },
            
            # ==================== EMPLOYEE DETAILS ====================
            # {
            #     "title": _("Employee Details"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Personal Info"),
            #             "icon": "person_outline",
            #             "link": admin_changelist("zktest", "employeepersonalinfo"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_employeepersonalinfo"),
            #         },
            #         {
            #             "title": _("Education"),
            #             "icon": "school",
            #             "link": admin_changelist("zktest", "employeeeducation"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_employeeeducation"),
            #         },
            #         {
            #             "title": _("Salary"),
            #             "icon": "payments",
            #             "link": admin_changelist("zktest", "employeesalary"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_employeesalary"),
            #         },
            #         {
            #             "title": _("Skills"),
            #             "icon": "psychology",
            #             "link": admin_changelist("zktest", "employeeskill"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_employeeskill"),
            #         },
            #     ],
            # },
            
            # ==================== LOCATION & NOTICES ====================
            # {
            #     "title": _("Location & Notices"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Locations"),
            #             "icon": "location_on",
            #             "link": admin_changelist("zktest", "location"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_location"),
            #         },
            #         {
            #             "title": _("User Locations"),
            #             "icon": "my_location",
            #             "link": admin_changelist("zktest", "userlocation"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_userlocation"),
            #         },
            #         {
            #             "title": _("Notices"),
            #             "icon": "notifications",
            #             "link": admin_changelist("zktest", "notice"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_notice"),
            #         },
            #     ],
            # },
            
            # ==================== ZK DEVICE MANAGEMENT ====================
            {
                "title": _("ZK Device Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ZK Devices"),
                        "icon": "devices",
                        "link": admin_changelist("zktest", "zkdevice"),
                        "permission": lambda request: request.user.has_perm("zktest.view_zkdevice"),
                        "badge": lambda request: __import__('zktest.models', fromlist=['ZKDevice']).ZKDevice.objects.filter(is_online=True).count(),
                    },
                    {
                        "title": _("Device Users"),
                        "icon": "badge",
                        "link": admin_changelist("zktest", "deviceuser"),
                        "permission": lambda request: request.user.has_perm("zktest.view_deviceuser"),
                    },
                    {
                        "title": _("Device Commands"),
                        "icon": "terminal",
                        "link": admin_changelist("zktest", "devicecommand"),
                        "permission": lambda request: request.user.has_perm("zktest.view_devicecommand"),
                        "badge": lambda request: __import__('zktest.models', fromlist=['DeviceCommand']).DeviceCommand.objects.filter(status='pending').count(),
                    },
                    {
                        "title": _("Device Heartbeats"),
                        "icon": "monitor_heart",
                        "link": admin_changelist("zktest", "deviceheartbeat"),
                        "permission": lambda request: request.user.has_perm("zktest.view_deviceheartbeat"),
                    },
                ],
            },
            

            
            # ==================== BIOMETRIC DATA ====================
            # {
            #     "title": _("Biometric Data"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Fingerprint Templates"),
            #             "icon": "fingerprint",
            #             "link": admin_changelist("zktest", "fingerprinttemplate"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_fingerprinttemplate"),
            #         },
            #         {
            #             "title": _("Face Templates"),
            #             "icon": "face",
            #             "link": admin_changelist("zktest", "facetemplate"),
            #             "permission": lambda request: request.user.has_perm("zktest.view_facetemplate"),
            #         },
            #     ],
            # },
                        # ==================== AUTHENTICATION ====================
            {
                "title": _("Authentication & Authorization"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },

        ],
    },
}
