# Generated by Django 5.2.8 on 2025-11-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='User ID')),
                ('face_index', models.SmallIntegerField(default=0, verbose_name='Face Index')),
                ('template_data', models.BinaryField(blank=True, null=True, verbose_name='Template Data')),
                ('template_size', models.IntegerField(default=0, verbose_name='Template Size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Template',
                'verbose_name_plural': 'Face Templates',
                'db_table': 'zk_face_templates',
                'ordering': ['device', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='User ID')),
                ('finger_index', models.SmallIntegerField(default=0, verbose_name='Finger Index')),
                ('template_data', models.BinaryField(blank=True, null=True, verbose_name='Template Data')),
                ('template_size', models.IntegerField(default=0, verbose_name='Template Size')),
                ('template_flag', models.SmallIntegerField(default=1, verbose_name='Template Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fingerprint Template',
                'verbose_name_plural': 'Fingerprint Templates',
                'db_table': 'zk_fingerprint_templates',
                'ordering': ['device', 'user_id', 'finger_index'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device', 'heartbeat_time'], name='zk_device_h_device__995b2e_idx'),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='zktest.zkdevice', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='fingerprinttemplate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='zktest.zkdevice', verbose_name='Device'),
        ),
        migrations.AlterUniqueTogether(
            name='facetemplate',
            unique_together={('device', 'user_id', 'face_index')},
        ),
        migrations.AlterUniqueTogether(
            name='fingerprinttemplate',
            unique_together={('device', 'user_id', 'finger_index')},
        ),
    ]
