# Generated by Django 5.2.8 on 2025-11-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zktest', '0002_facetemplate_fingerprinttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('adms', 'ADMS Push'), ('tcp', 'TCP/PyZK Pull'), ('manual', 'Manual Entry')], default='adms', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='connection_type',
            field=models.CharField(choices=[('adms', 'ADMS (Push Protocol)'), ('tcp', 'TCP/IP (PyZK)'), ('both', 'Both ADMS + TCP')], default='adms', help_text='ADMS for push-based, TCP for old devices using PyZK', max_length=20, verbose_name='Connection Type'),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='port',
            field=models.IntegerField(default=4370, help_text='TCP port for PyZK connection', verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='tcp_password',
            field=models.CharField(blank=True, help_text='Comm key for PyZK', max_length=50, verbose_name='Device Password'),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='tcp_timeout',
            field=models.IntegerField(default=5, verbose_name='TCP Timeout (sec)'),
        ),
        migrations.CreateModel(
            name='TCPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('users', 'Users'), ('attendance', 'Attendance'), ('fingerprints', 'Fingerprints'), ('faces', 'Faces'), ('all', 'All Data')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('records_found', models.IntegerField(default=0, verbose_name='Records Found')),
                ('records_synced', models.IntegerField(default=0, verbose_name='Records Synced')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Records Failed')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_sync_logs', to='zktest.zkdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'TCP Sync Log',
                'verbose_name_plural': 'TCP Sync Logs',
                'db_table': 'zk_tcp_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
