# Generated by Django 5.2.8 on 2025-12-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zktest', '0003_attendancelog_source_zkdevice_connection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='punch_type',
            field=models.SmallIntegerField(choices=[(0, 'Check In'), (1, 'Check Out'), (2, 'Break Out'), (3, 'Break In'), (4, 'OT In'), (5, 'OT Out'), (255, 'Punch')], default=0, verbose_name='Punch Type'),
        ),
    ]
