# Generated by Django 5.2.8 on 2025-12-04 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zktest', '0004_alter_attendancelog_punch_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='portal_user',
            field=models.OneToOneField(blank=True, help_text='Link to Django user account for web portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zktest_employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Portal User'),
        ),
    ]
