# Generated by Django 5.2.8 on 2025-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zktest', '0005_employee_portal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekend_allowance',
            field=models.BooleanField(default=True, help_text='If enabled, employee gets 15 hours fixed salary on weekend work. If ANY absent day in period, weekend benefits are removed.', verbose_name='Weekend Allowance (15 hrs/day)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekend_days',
            field=models.CharField(default='friday', help_text="Comma-separated day names (e.g., 'friday' or 'saturday,sunday')", max_length=100, verbose_name='Weekend Days'),
        ),
    ]
